import { StyleSheet } from 'react-native';

import { colors } from '@/constants/colors';

export const childrenStyles = StyleSheet.create({
  content: {
    gap: 22,
  },
  section: {
    gap: 12,
  },
  sectionTitle: {
    fontSize: 20,
    lineHeight: 26,
    color: colors.grayscale[1000],
  },
  selectorScrollContent: {
    paddingRight: 24,
    gap: 10,
  },
  childChip: {
    minWidth: 104,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderRadius: 18,
    backgroundColor: colors.grayscale[100],
    borderWidth: 2,
    borderColor: colors.grayscale[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  childChipSelected: {
    backgroundColor: '#FFF3DA',
    borderColor: '#FFCF7D',
  },
  childChipText: {
    fontSize: 18,
    lineHeight: 24,
    color: colors.grayscale[1000],
  },
  addChildChip: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 18,
    backgroundColor: colors.grayscale[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  addChildChipText: {
    fontSize: 18,
    lineHeight: 24,
    color: colors.grayscale[1000],
  },
  boardCard: {
    flexDirection: 'row',
    gap: 14,
    borderRadius: 22,
    backgroundColor: colors.grayscale[100],
    padding: 16,
    borderWidth: 1,
    borderColor: '#F5EAD5',
  },
  boardInfo: {
    flex: 1,
    gap: 10,
    justifyContent: 'center',
  },
  boardInfoText: {
    fontSize: 17,
    lineHeight: 24,
    color: '#4F4A44',
  },
  stickerActionColumn: {
    justifyContent: 'space-between',
    gap: 10,
  },
  stickerButton: {
    width: 114,
    minHeight: 146,
    borderRadius: 18,
    backgroundColor: '#FFF3DA',
    borderWidth: 2,
    borderColor: '#FFCF7D',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 10,
    position: 'relative',
  },
  stickerButtonArt: {
    fontSize: 42,
    lineHeight: 44,
    color: colors.grayscale[1000],
    marginBottom: 6,
  },
  stickerButtonText: {
    fontSize: 16,
    lineHeight: 22,
    color: colors.grayscale[1000],
    textAlign: 'center',
  },
  notificationDot: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#FF3B30',
  },
  missionList: {
    gap: 12,
  },
  missionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderRadius: 22,
    backgroundColor: colors.grayscale[100],
    borderWidth: 1.5,
    borderColor: '#B9B2A7',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  missionEmoji: {
    fontSize: 32,
    lineHeight: 36,
  },
  missionCopy: {
    flex: 1,
    gap: 2,
  },
  missionTitle: {
    fontSize: 20,
    lineHeight: 26,
    color: colors.grayscale[1000],
  },
  missionMeta: {
    fontSize: 16,
    lineHeight: 21,
    color: '#4F4A44',
  },
  chevron: {
    fontSize: 28,
    lineHeight: 28,
    color: colors.grayscale[1000],
  },
  emptyCard: {
    borderRadius: 22,
    backgroundColor: colors.grayscale[100],
    paddingHorizontal: 18,
    paddingVertical: 20,
  },
  emptyBoardCard: {
    borderRadius: 22,
    backgroundColor: colors.grayscale[100],
    paddingHorizontal: 24,
    paddingVertical: 36,
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyBoardText: {
    fontSize: 16,
    lineHeight: 24,
    color: colors.grayscale[1000],
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 16,
    lineHeight: 22,
    color: '#6D665E',
    textAlign: 'center',
  },
  primaryButton: {
    borderRadius: 22,
    backgroundColor: '#FFF1CC',
    borderWidth: 2,
    borderColor: '#FFCF7D',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
  },
  primaryButtonText: {
    fontSize: 22,
    lineHeight: 28,
    color: colors.grayscale[1000],
  },
  editLink: {
    fontSize: 16,
    lineHeight: 22,
    color: '#5A5146',
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  emptyState: {
    gap: 16,
    paddingTop: 40,
  },
  emptyStateText: {
    fontSize: 18,
    lineHeight: 24,
    textAlign: 'center',
    color: '#5A5146',
  },
});
